In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
a.dtype

dtype('int64')

In [3]:
np.array?

In [4]:
a.dtype?

In [9]:
a.astype(np.float)

array([1., 2., 3., 4.])

In [12]:
b = np.array([[100, 101, 102],[201, 202, 203], [301, 302, 303]])
b

array([[100, 101, 102],
       [201, 202, 203],
       [301, 302, 303]])

In [13]:
b[0]

array([100, 101, 102])

In [14]:
lst = [10, 20, 30]
lst[0]

10

In [15]:
b[5]

IndexError: index 5 is out of bounds for axis 0 with size 3

|姓名|分数|
|---|---|
|张三|100|
|李四|99 |
|王五|98 |

In [16]:
import pandas as pd
s = pd.Series([100, 99, 98], index=["zhang", "wang", "li"])

In [17]:
s

zhang    100
wang      99
li        98
dtype: int64

In [18]:
s['zhang']

100

In [19]:
s[0]

100

In [20]:
pd.DataFrame?

In [22]:
df = pd.DataFrame(b, columns=['first', 'second', 'three'], index=['one', 'two', 'three'])
df

first  second  three
one      100     101    102
two      201     202    203
three    301     302    303

In [24]:
# source: https://github.com/qiwsir/DataSet/tree/master/jiangsu/city_population.csv
pd.read_csv("/Users/qiwsir/Documents/Codes/DataSet/jiangsu/city_population.csv")

name      area  population   longd   latd
0    南京市   6582.31     8004680  118.78  32.04
1    无锡市   4787.61     6372624  120.29  31.59
2    徐州市  11764.88     8580500  117.20  34.26
3    常州市   4384.57     4591972  119.95  31.79
4    苏州市   8488.42    10465994  120.62  31.32
5    南通市   8001.00     7282835  120.86  32.01
6   连云港市   7615.29     4393914  119.16  34.59
7    淮安市   9949.97     4799889  119.15  33.50
8    盐城市  16972.42     7260240  120.13  33.38
9    扬州市   6591.21     4459760  119.42  32.39
10   镇江市   3840.32     3113384  119.44  32.20
11   泰州市   5787.26     4618558  119.90  32.49
12   宿迁市   8555.00     4715553  118.30  33.96

In [26]:
pd.read_csv("/Users/qiwsir/Documents/Codes/DataSet/jiangsu/city_population.csv", index_col='name')

area  population   longd   latd
name                                     
南京市    6582.31     8004680  118.78  32.04
无锡市    4787.61     6372624  120.29  31.59
徐州市   11764.88     8580500  117.20  34.26
常州市    4384.57     4591972  119.95  31.79
苏州市    8488.42    10465994  120.62  31.32
南通市    8001.00     7282835  120.86  32.01
连云港市   7615.29     4393914  119.16  34.59
淮安市    9949.97     4799889  119.15  33.50
盐城市   16972.42     7260240  120.13  33.38
扬州市    6591.21     4459760  119.42  32.39
镇江市    3840.32     3113384  119.44  32.20
泰州市    5787.26     4618558  119.90  32.49
宿迁市    8555.00     4715553  118.30  33.96